language: node_js
node_js:
  - "6.0"
script:
  - echo "Building"
  - npm install
  - bower install
  - gulp build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
