language: node_js
node_js:
  - "6.0"
branches:
  only:
    - main
notifications:
  slack: willysbrewing:sbY2heRtEqq1ukQ804xRgymZ
install:
  - npm install -g firebase-tools
script:
  - echo "Building"
  - npm install
  - bower install
  - gulp build
after_success:
  - firebase use willys-4fbc0
  - firebase deploy --token $FIREBASE_TOKEN
